version: '3.8'

services:
  postgres:
     container_name: gestao_vagas_postgres
     image: postgres
     ports:
      - 5432:5432
environment:
        - POSTGRES_USER=elisson
        - POSTGRES_PASSWORD=elisson
        - POSTGRES_DB=gestão_vagas
    